export const typeEmojis: Record<string, string> = {
  Water: "💧",
  Fire: "🔥",
  Grass: "🌿",
  Electric: "⚡",
  Psychic: "🔮",
  Ice: "❄️",
  Dragon: "🐉",
  Ghost: "👻",
  Dark: "🌑",
  Fairy: "🧚",
  Normal: "⚪",
  Bug: "🐛",
  Rock: "🪨",
  Ground: "🌍",
  Flying: "🕊️",
  Steel: "🔩",
  Poison: "☠️",
  Fighting: "🥊",
}
